services:
  grafana-server:
    build: ./docker/grafana
    container_name: grafana-server
    ports:
    - 3030:3030
    volumes:
      - ./docker/grafana/provisioning:/etc/grafana/provisioning
      - ./docker/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./docker/grafana/dashboards:/var/lib/grafana/dashboards

  prometheus-server:
    build: ./docker/prometheus
    container_name: prometheus-server
    ports:
    - 9091:9090
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
