spring:
  application:
    name: vets-service
  config:
    import: configserver:http://config-server:8888:${CONFIG_SERVER_URL:http://localhost:8888/}
  cache:
    cache-names: vets
  profiles:
    active: production
  zipkin:
    base-url: http://tracing-server:9411
  management:
    endpoints:
      web:
        exposure:
          include: health, info, prometheus
    tracing:
      sampling:
        probability: 1.0

---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888
