spring:
  application:
    name: visits-service
  config:
    import: configserver:${CONFIG_SERVER_URL:http://config-server:8888/}
  zipkin:
    baseUrl: http://tracing-server:9411
  management:
    endpoints:
      web:
        exposure:
          include: health, info, prometheus, metrics
    tracing:
      sampling:
        probability: 1.0
    endpoint:
      prometheus:
        enabled: true


---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888
