spring:
  application:
    name: customers-service
  config:
    import: configserver:${CONFIG_SERVER_URL:http://config-server:8888/}
  zipkin:
    baseUrl: http://tracing-server:9411
  management:
    endpoints:
      web:
        exposure:
          include: health, info, prometheus
    tracing:
      sampling:
        probability: 1.0


---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888
