spring:
  application:
    name: customers-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
  zipkin:
    baseUrl: http://tracing-server:9411
  sleuth:
    sampler:
      probability: 1.0


---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888
