# config file version
apiVersion: 1

# list of datasources to insert/update depending what's available in the database
datasources:
- name: Loki
  type: loki
  access: proxy
  url: http://loki-stack.loki.svc.cluster.local:3100
  is_default: false
  editable: true
